feat: add config definition
RWTH-TIME/scystream pull request #27
Opened 2024-08-13 16:05 UTC by PaulKalho

2024-08-28 18:02 UTC, PaulKalho commented
Tested and works. R4R @mottegk @use-to

2024-09-04 01:48 UTC, use-to requested changes
Good pull request providing important traction. A few requests as this is a pivotal change.

2024-09-04 01:48 UTC, use-to commented on docker-compose.yml
> +      - "8008:80"
Unnecessary change

2024-09-04 01:48 UTC, use-to commented on docker-compose.yml
> +      EXTERNAL_URL: "http://localhost:8008"
See above

2024-09-04 01:48 UTC, use-to commented on frontend/mutations/userMutation.ts
> +      } catch (error) {
Use react-query's error handling instead.

2024-09-06 11:12 UTC, use-to approved these changes

2024-09-06 11:28 UTC, merged