Issue/36 dag configuration translator
RWTH-TIME/scystream pull request #71
Opened 2024-11-24 12:19 UTC by mottegk

Converts our project and block model into a python file for airflow. 
Also validates the DAG to be acyclic.

2025-01-21 13:28 UTC, PaulKalho requested changes

2025-01-21 13:28 UTC, PaulKalho commented on core/alembic/versions/bf8bb8e597db_add_names_to_block_dependencies_foreign_.py
> +    # ### end Alembic commands ###
empty migration

2025-01-21 13:28 UTC, PaulKalho commented on core/conftest.py
> +Base.metadata.clear()
This is needed, right?

2025-01-21 13:28 UTC, PaulKalho commented on core/services/workflow_service/controllers/DAG_translator.py
> +                # pipeline=str(project.pipeline_uuid),
Why are these commented out?

2025-01-21 13:28 UTC, PaulKalho commented on core/services/workflow_service/controllers/project_controller.py
Did you test the functions in this file?

Imo we could create an Issue for testing in general, and write tests for all of our controllers and/or internal functions

2025-01-21 13:28 UTC, PaulKalho commented on core/services/workflow_service/views/project.py
> +            data.name, data.user_uuid
Why not extracting the user_uuid from the token?

2025-01-21 13:28 UTC, PaulKalho commented on core/services/workflow_service/views/project.py
> +        raise handle_error(e)
As already written in the corresponding controller function & discussed on Slack. I suppose we do not need this endpoint. Do you agree? Or am I missing some use-cases here?

2025-01-21 14:42 UTC, mottegk commented on core/services/workflow_service/controllers/DAG_translator.py
> +def translate_project_to_dag(project_uuid: UUID):
It's called from the dag view route wich I tested. As I was unable to create a correct Entrypoint the part after the error for incorrect Entrypoint could not be tested up till now. The CRUD logic for Entrypoints would be necessary for this.

2025-01-21 14:53 UTC, PaulKalho commented on core/conftest.py
> +Base.metadata.clear()
Yes, if it's not working, delete it.

2025-02-11 18:51 UTC, PaulKalho approved these changes

2025-02-11 18:51 UTC, merged